baseURL: "https://asadtariq.org/"
title: Asad Tariq
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Courses
          url: courses/
          weight: 1

params:
    description: "This website hosts Asad Tariq's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Asad Tariq
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["courses", "papers"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Asad Tariq
          subtitle: "I am a Dean's Fellow in the Computer Science Department at Habib University, Karachi, Pakistan. My research primarily focuses on the simulation and analysis of dynamic and complex human social networks and game theory."
          imageUrl: "pfp.jpg"
          imageWidth: 180
          imageHeight: 180
          buttons:
            - name: Courses
              url: courses/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:asadtariq1999@gmail.com
        - name: Office Hours
          url: officehours/
        - name: GitHub
          url: https://github.com/Asad-Tariq
        - name: LinkedIn
          url: https://www.linkedin.com/in/asad-tariq-1999atd/

    assets:
        disableScrollBarStyle: true
        favicon: "static/favicon.ico"
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Asad Tariq"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
